/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  const now = new Date()
  const oneWeek = now.setDate(now.getDate() + 1 * 7)
  await knex('pantry_items').del()
  await knex('pantry_items').insert([
    {
      id: 1,
      quantity: 6,
      name: 'Apples',
      category: null,
      brand: null,
      image: '',
      best_before: oneWeek,
      is_fav: false,
      created_by: 1234,
    },
    {
      id: 2,
      quantity: 2,
      name: 'Onions',
      category: null,
      brand: null,
      image: '',
      best_before: oneWeek,
      is_fav: false,
      created_by: 1234,
    },

    {
      id: 3,
      quantity: 5,
      name: 'Garlic',
      category: null,
      brand: null,
      image: '',
      best_before: oneWeek,
      is_fav: false,
      created_by: 1234,
    },
    {
      id: 4,
      quantity: 1,
      name: 'Oat milk',
      category: null,
      brand: null,
      image: '',
      best_before: oneWeek,
      is_fav: false,
      created_by: 1234,
    },
    {
      id: 5,
      quantity: 1,
      name: 'Bread',
      category: null,
      brand: null,
      image: '',
      best_before: oneWeek,
      is_fav: false,
      created_by: 1234,
    },
    {
      id: 6,
      quantity: 3,
      name: 'Tofu',
      category: null,
      brand: null,
      image: '',
      best_before: oneWeek,
      is_fav: false,
      created_by: 1234,
    },
    {
      id: 7,
      quantity: 1,
      name: 'Toilet cleaner',
      category: null,
      brand: null,
      image: '',
      best_before: oneWeek,
      is_fav: false,
      created_by: 1234,
    },
    {
      id: 8,
      quantity: 0,
      name: 'Steak',
      category: null,
      brand: null,
      image: '',
      best_before: oneWeek,
      is_fav: false,
      created_by: 1234,
    },
    {
      id: 9,
      quantity: 1,
      name: 'Cumin',
      category: null,
      brand: null,
      image: '',
      best_before: oneWeek,
      is_fav: false,
      created_by: 1234,
    },
    {
      id: 10,
      quantity: 24,
      name: 'Beers',
      category: null,
      brand: null,
      image: '',
      best_before: oneWeek,
      is_fav: false,
      created_by: 1234,
    },
    {
      id: 11,
      quantity: 4,
      name: 'Sheep Intestines',
      category: 1,
      brand: null,
      image: '',
      best_before: oneWeek,
      is_fav: false,
      created_by: 4321,
    },
  ])
}
